# Generated by Django 3.2.3 on 2021-05-22 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='makeevent',
            name='event_contact',
            field=models.CharField(default='', max_length=13),
        ),
        migrations.AlterField(
            model_name='makeevent',
            name='event_desc',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='makeevent',
            name='event_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='makeevent',
            name='event_poster',
            field=models.ImageField(default='', upload_to='mySite/images'),
        ),
    ]
