# Generated by Django 3.2.3 on 2021-05-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySite', '0002_auto_20210522_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='makeevent',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
