# Generated by Django 3.2.3 on 2021-05-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySite', '0004_alter_makeevent_event_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makeevent',
            name='event_poster',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
