# Generated by Django 3.2.3 on 2021-05-23 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mySite', '0006_alter_makeevent_event_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='makeevent',
            name='user_id',
        ),
    ]
