# Generated by Django 3.2.3 on 2021-05-24 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mySite', '0008_registerevent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registerEvent',
        ),
    ]
