# Generated by Django 3.2.3 on 2021-05-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySite', '0009_delete_registerevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='registerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('eventdesc', models.CharField(default='', max_length=300)),
                ('eventcontact', models.CharField(default='', max_length=13)),
            ],
        ),
    ]
