# Generated by Django 3.2.3 on 2021-05-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySite', '0010_registerevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerevent',
            name='Event_name',
        ),
        migrations.AddField(
            model_name='registerevent',
            name='eventname',
            field=models.CharField(default='', max_length=50),
        ),
    ]
