# Generated by Django 3.2.3 on 2021-05-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySite', '0011_auto_20210524_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerevent',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
