# Generated by Django 3.2.3 on 2021-05-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySite', '0012_alter_registerevent_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerevent',
            name='eventname',
            field=models.TextField(default='', max_length=50),
        ),
    ]
