# Generated by Django 3.2.3 on 2021-05-24 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mySite', '0013_alter_registerevent_eventname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerevent',
            old_name='eventcontact',
            new_name='event_contact',
        ),
        migrations.RenameField(
            model_name='registerevent',
            old_name='eventdesc',
            new_name='event_desc',
        ),
        migrations.RenameField(
            model_name='registerevent',
            old_name='eventname',
            new_name='event_name',
        ),
    ]
