# Generated by Django 3.2.3 on 2021-05-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mySite', '0014_auto_20210524_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='myEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myeve_name', models.CharField(max_length=50)),
                ('myeve_username', models.CharField(max_length=50)),
                ('myeve_email', models.CharField(max_length=50)),
                ('myeve_desc', models.CharField(max_length=300)),
                ('myeve_contact', models.CharField(max_length=13)),
            ],
        ),
    ]
