# Generated by Django 3.2.3 on 2021-05-25 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mySite', '0015_myevent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registerEvent',
        ),
    ]
